excerpt_separator: ""
# pygments: true
highlighter: rouge
markdown: kramdown
url: https://shengshampoo.github.io
title: Shengshampoo Github_Page
tagline: Post anything I understand, from anywhere I attend.
description: Shengshampoo Github Page.
paginate: 1
